2020-10-25 09:56:36,304 - Shuake.py[line:641] - INFO: 运行
2020-10-25 10:00:01,972 - Shuake.py[line:641] - INFO: 运行
2020-10-25 10:11:18,093 - Shuake.py[line:643] - INFO: 运行
2020-10-25 10:11:22,181 - Shuake.py[line:566] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 550, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:11:22,184 - Shuake.py[line:567] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:11:24,352 - Shuake.py[line:566] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 550, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:11:24,353 - Shuake.py[line:567] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:11:24,710 - Shuake.py[line:566] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 550, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:11:24,711 - Shuake.py[line:567] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:11:24,961 - Shuake.py[line:566] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 550, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:11:24,962 - Shuake.py[line:567] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:11:26,568 - Shuake.py[line:566] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 550, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:11:26,569 - Shuake.py[line:567] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:12:50,151 - Shuake.py[line:643] - INFO: 运行
2020-10-25 10:21:02,683 - Shuake.py[line:566] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 550, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:21:02,685 - Shuake.py[line:567] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:24:07,761 - Shuake.py[line:643] - INFO: 运行
2020-10-25 10:29:52,106 - Shuake.py[line:566] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 550, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:29:52,108 - Shuake.py[line:567] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:36:04,081 - Shuake.py[line:653] - INFO: 运行
2020-10-25 10:36:06,629 - Shuake.py[line:259] - ERROR: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 255, in shuake
    self.read_book(cardInfo, reportInfo, knowledge, scoreInfo)
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 475, in read_book
    ('knowledgeid', knowledge["knowlegedId"]),
KeyError: 'knowlegedId'
2020-10-25 10:36:06,630 - Shuake.py[line:260] - INFO: 18925468581	刷课意外
2020-10-25 10:36:19,358 - Shuake.py[line:653] - INFO: 运行
2020-10-25 10:36:21,479 - Shuake.py[line:259] - ERROR: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 255, in shuake
    self.read_book(cardInfo, reportInfo, knowledge, scoreInfo)
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 475, in read_book
    ('knowledgeid', knowledge["knowlegedId"]),
KeyError: 'knowlegedId'
2020-10-25 10:36:21,481 - Shuake.py[line:260] - INFO: 18925468581	刷课意外
2020-10-25 10:36:48,551 - Shuake.py[line:654] - INFO: 运行
2020-10-25 10:37:48,379 - Shuake.py[line:654] - INFO: 运行
2020-10-25 10:37:53,826 - Shuake.py[line:577] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 561, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:37:53,829 - Shuake.py[line:578] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:37:56,388 - Shuake.py[line:577] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 561, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:37:56,389 - Shuake.py[line:578] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:37:56,693 - Shuake.py[line:577] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 561, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:37:56,693 - Shuake.py[line:578] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:37:58,374 - Shuake.py[line:577] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 561, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:37:58,374 - Shuake.py[line:578] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:39:50,811 - Shuake.py[line:654] - INFO: 运行
2020-10-25 10:42:51,233 - Shuake.py[line:654] - INFO: 运行
2020-10-25 10:48:18,177 - Shuake.py[line:657] - INFO: 运行
2020-10-25 10:55:22,452 - Shuake.py[line:656] - INFO: 运行
2020-10-25 10:55:25,216 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:55:25,218 - Shuake.py[line:580] - INFO: 18740455867	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:55:34,476 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:55:34,477 - Shuake.py[line:580] - INFO: 15829380839	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:55:34,798 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:55:34,798 - Shuake.py[line:580] - INFO: 15829380839	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:55:39,899 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:55:39,900 - Shuake.py[line:580] - INFO: 17561925661	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:55:40,207 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:55:40,208 - Shuake.py[line:580] - INFO: 17561925661	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:55:41,876 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:55:41,877 - Shuake.py[line:580] - INFO: 17561925661	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:55:44,831 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:55:44,832 - Shuake.py[line:580] - INFO: 18740455867	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:55:45,056 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:55:45,057 - Shuake.py[line:580] - INFO: 15970198033	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:55:45,194 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:55:45,195 - Shuake.py[line:580] - INFO: 18740455867	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:55:45,390 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:55:45,391 - Shuake.py[line:580] - INFO: 15970198033	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:55:47,286 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:55:47,287 - Shuake.py[line:580] - INFO: 15970198033	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:55:49,765 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:55:49,766 - Shuake.py[line:580] - INFO: 18182699011	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:55:50,062 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:55:50,062 - Shuake.py[line:580] - INFO: 18182699011	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:55:51,693 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:55:51,694 - Shuake.py[line:580] - INFO: 18182699011	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:55:52,339 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:55:52,340 - Shuake.py[line:580] - INFO: 15829380839	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:55:55,845 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:55:55,846 - Shuake.py[line:580] - INFO: 15829380839	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:55:56,433 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:55:56,434 - Shuake.py[line:580] - INFO: 13619506250	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:55:57,745 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:55:57,749 - Shuake.py[line:580] - INFO: 18740455867	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:56:02,174 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:56:02,175 - Shuake.py[line:580] - INFO: 15037671931	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:56:05,692 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:56:05,694 - Shuake.py[line:580] - INFO: 13619506250	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:56:06,336 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:56:06,342 - Shuake.py[line:580] - INFO: 13619506250	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:56:06,785 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:56:06,786 - Shuake.py[line:580] - INFO: 13619506250	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:56:09,133 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:56:09,134 - Shuake.py[line:580] - INFO: 13619506250	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:56:12,244 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:56:12,245 - Shuake.py[line:580] - INFO: 17691183327	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:56:16,962 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:56:16,963 - Shuake.py[line:580] - INFO: 15037671931	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:56:17,370 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:56:17,371 - Shuake.py[line:580] - INFO: 15037671931	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:56:17,690 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:56:17,691 - Shuake.py[line:580] - INFO: 15037671931	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:56:19,974 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:56:19,975 - Shuake.py[line:580] - INFO: 15037671931	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:56:22,715 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:56:22,716 - Shuake.py[line:580] - INFO: 15638127287	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:56:28,399 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:56:28,400 - Shuake.py[line:580] - INFO: 18700182108	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:56:48,056 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:56:48,062 - Shuake.py[line:580] - INFO: 17809297831	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:56:48,161 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:56:48,161 - Shuake.py[line:580] - INFO: 15702959565	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:56:48,678 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:56:48,679 - Shuake.py[line:580] - INFO: 15638127287	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:56:49,561 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:56:49,578 - Shuake.py[line:580] - INFO: 18182699011	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:56:49,635 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:56:49,640 - Shuake.py[line:580] - INFO: 15638127287	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:56:50,113 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:56:50,113 - Shuake.py[line:580] - INFO: 18182699011	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:56:50,171 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:56:50,184 - Shuake.py[line:580] - INFO: 15638127287	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:56:52,649 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:56:52,650 - Shuake.py[line:580] - INFO: 15638127287	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:56:55,479 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:56:55,480 - Shuake.py[line:580] - INFO: 15970198033	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:56:55,884 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:56:55,885 - Shuake.py[line:580] - INFO: 15970198033	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:56:58,381 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:56:58,382 - Shuake.py[line:580] - INFO: 18700182108	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:56:58,810 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:56:58,811 - Shuake.py[line:580] - INFO: 18700182108	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:56:59,147 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:56:59,147 - Shuake.py[line:580] - INFO: 18700182108	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:57:03,735 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:57:03,736 - Shuake.py[line:580] - INFO: 15081150997	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:57:04,266 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:57:04,267 - Shuake.py[line:580] - INFO: 15081150997	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:57:04,688 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:57:04,688 - Shuake.py[line:580] - INFO: 15081150997	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:57:07,166 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:57:07,167 - Shuake.py[line:580] - INFO: 15081150997	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:57:07,395 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:57:07,396 - Shuake.py[line:580] - INFO: 17561925661	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:57:07,748 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:57:07,749 - Shuake.py[line:580] - INFO: 17561925661	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:57:08,461 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:57:08,462 - Shuake.py[line:580] - INFO: 17691183327	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:57:09,034 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:57:09,038 - Shuake.py[line:580] - INFO: 17691183327	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:57:09,509 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:57:09,511 - Shuake.py[line:580] - INFO: 17691183327	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:57:11,581 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:57:11,582 - Shuake.py[line:580] - INFO: 17691183327	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:57:18,617 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:57:18,618 - Shuake.py[line:580] - INFO: 15970198033	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:57:19,945 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:57:19,946 - Shuake.py[line:580] - INFO: 18740455867	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:57:22,775 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:57:22,776 - Shuake.py[line:580] - INFO: 15970198033	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:57:45,298 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:57:45,299 - Shuake.py[line:580] - INFO: 15702959565	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:57:45,881 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:57:45,882 - Shuake.py[line:580] - INFO: 15702959565	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:57:46,342 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:57:46,342 - Shuake.py[line:580] - INFO: 15702959565	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:57:48,869 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:57:48,870 - Shuake.py[line:580] - INFO: 15702959565	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:57:49,348 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:57:49,349 - Shuake.py[line:580] - INFO: 17809297831	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:57:49,760 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:57:49,761 - Shuake.py[line:580] - INFO: 17809297831	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:57:50,097 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:57:50,100 - Shuake.py[line:580] - INFO: 17809297831	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:57:52,208 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:57:52,209 - Shuake.py[line:580] - INFO: 17809297831	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:58:04,252 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:58:04,253 - Shuake.py[line:580] - INFO: 13619506250	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:58:04,577 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:58:04,578 - Shuake.py[line:580] - INFO: 13619506250	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:58:29,948 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:58:29,949 - Shuake.py[line:580] - INFO: 15081150997	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 10:58:30,284 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 10:58:30,285 - Shuake.py[line:580] - INFO: 15081150997	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:00:11,904 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:00:11,905 - Shuake.py[line:580] - INFO: 18700182108	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:00:13,703 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:00:13,704 - Shuake.py[line:580] - INFO: 13098880838	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:00:24,438 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:00:24,439 - Shuake.py[line:580] - INFO: 18182699011	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:00:26,286 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:00:26,287 - Shuake.py[line:580] - INFO: 13619506250	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:00:28,022 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:00:28,023 - Shuake.py[line:580] - INFO: 18182699011	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:00:35,211 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:00:35,212 - Shuake.py[line:580] - INFO: 13619506250	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:00:36,308 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:00:36,314 - Shuake.py[line:580] - INFO: 15081150997	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:00:57,463 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:00:57,464 - Shuake.py[line:580] - INFO: 17561925661	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:01:00,801 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:01:00,802 - Shuake.py[line:580] - INFO: 17561925661	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:01:04,496 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:01:04,496 - Shuake.py[line:580] - INFO: 13098880838	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:01:05,190 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:01:05,191 - Shuake.py[line:580] - INFO: 13098880838	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:01:05,657 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:01:05,657 - Shuake.py[line:580] - INFO: 13098880838	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:01:08,009 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:01:08,009 - Shuake.py[line:580] - INFO: 13098880838	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:03:04,895 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:03:04,896 - Shuake.py[line:580] - INFO: 15037671931	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:03:05,193 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:03:05,194 - Shuake.py[line:580] - INFO: 15037671931	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:03:06,923 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:03:06,924 - Shuake.py[line:580] - INFO: 15037671931	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:03:36,283 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:03:36,284 - Shuake.py[line:580] - INFO: 15037671931	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:06:13,385 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:06:13,386 - Shuake.py[line:580] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:06:13,702 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:06:13,702 - Shuake.py[line:580] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:09:04,793 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:09:04,794 - Shuake.py[line:580] - INFO: 15638127287	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:09:05,131 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:09:05,132 - Shuake.py[line:580] - INFO: 15638127287	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:09:08,822 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:09:08,822 - Shuake.py[line:580] - INFO: 17691183327	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:09:09,154 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:09:09,155 - Shuake.py[line:580] - INFO: 17691183327	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:12:11,507 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:12:11,508 - Shuake.py[line:580] - INFO: 15702959565	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:14:07,565 - Shuake.py[line:259] - ERROR: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 253, in shuake
    self.watch_video(cardInfo, reportInfo, knowledge, scoreInfo)
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 309, in watch_video
    params=params)
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 30, in get
    return super(Session,self).get(*args,**kwargs,timeout=self.timeOut)
  File "D:\ProgramData\Anaconda3\envs\spy\lib\site-packages\requests\sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\spy\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\ProgramData\Anaconda3\envs\spy\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\spy\lib\site-packages\requests\adapters.py", line 445, in send
    timeout=timeout
  File "D:\ProgramData\Anaconda3\envs\spy\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "D:\ProgramData\Anaconda3\envs\spy\lib\site-packages\urllib3\connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "D:\ProgramData\Anaconda3\envs\spy\lib\site-packages\urllib3\connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "D:\ProgramData\Anaconda3\envs\spy\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "D:\ProgramData\Anaconda3\envs\spy\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "D:\ProgramData\Anaconda3\envs\spy\lib\http\client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "D:\ProgramData\Anaconda3\envs\spy\lib\socket.py", line 590, in readinto
    except timeout:
TypeError: catching classes that do not inherit from BaseException is not allowed
2020-10-25 11:14:07,577 - Shuake.py[line:260] - INFO: 15829380839	刷课意外
2020-10-25 11:15:10,228 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:15:10,229 - Shuake.py[line:580] - INFO: 18700182108	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:15:10,536 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:15:10,537 - Shuake.py[line:580] - INFO: 18700182108	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:16:13,197 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:16:13,198 - Shuake.py[line:580] - INFO: 15970198033	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:17:12,956 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:17:12,957 - Shuake.py[line:580] - INFO: 15702959565	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:21:07,080 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:21:07,081 - Shuake.py[line:580] - INFO: 13098880838	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:21:07,411 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:21:07,411 - Shuake.py[line:580] - INFO: 13098880838	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:29:45,686 - Shuake.py[line:656] - INFO: 运行
2020-10-25 11:30:23,258 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:30:23,259 - Shuake.py[line:580] - INFO: 18845142702	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:31:00,352 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:31:00,352 - Shuake.py[line:580] - INFO: 15970198033	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:32:47,084 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:32:47,084 - Shuake.py[line:580] - INFO: 18925468581	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:35:25,017 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:35:25,017 - Shuake.py[line:580] - INFO: 17691183327	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:38:08,958 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:38:08,958 - Shuake.py[line:580] - INFO: 15638127287	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:39:43,255 - Shuake.py[line:656] - INFO: 运行
2020-10-25 11:40:21,805 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:40:21,807 - Shuake.py[line:580] - INFO: 18845142702	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:40:42,208 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:40:42,209 - Shuake.py[line:580] - INFO: 15970198033	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:41:21,931 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:41:21,932 - Shuake.py[line:580] - INFO: 15638127287	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:41:38,980 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:41:38,981 - Shuake.py[line:580] - INFO: 15081150997	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:43:24,286 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:43:24,286 - Shuake.py[line:580] - INFO: 18700182108	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:46:49,234 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:46:49,235 - Shuake.py[line:580] - INFO: 13098880838	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:53:14,943 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:53:14,943 - Shuake.py[line:580] - INFO: 15702959565	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 11:53:22,534 - Shuake.py[line:259] - ERROR: 
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\spy\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "D:\ProgramData\Anaconda3\envs\spy\lib\site-packages\urllib3\connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "D:\ProgramData\Anaconda3\envs\spy\lib\site-packages\urllib3\connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "D:\ProgramData\Anaconda3\envs\spy\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "D:\ProgramData\Anaconda3\envs\spy\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "D:\ProgramData\Anaconda3\envs\spy\lib\http\client.py", line 265, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\spy\lib\site-packages\requests\adapters.py", line 445, in send
    timeout=timeout
  File "D:\ProgramData\Anaconda3\envs\spy\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "D:\ProgramData\Anaconda3\envs\spy\lib\site-packages\urllib3\util\retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "D:\ProgramData\Anaconda3\envs\spy\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "D:\ProgramData\Anaconda3\envs\spy\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "D:\ProgramData\Anaconda3\envs\spy\lib\site-packages\urllib3\connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "D:\ProgramData\Anaconda3\envs\spy\lib\site-packages\urllib3\connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "D:\ProgramData\Anaconda3\envs\spy\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "D:\ProgramData\Anaconda3\envs\spy\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "D:\ProgramData\Anaconda3\envs\spy\lib\http\client.py", line 265, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 253, in shuake
    self.watch_video(cardInfo, reportInfo, knowledge, scoreInfo)
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 309, in watch_video
    params=params)
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 30, in get
    return super(Session,self).get(*args,**kwargs,timeout=self.timeOut)
  File "D:\ProgramData\Anaconda3\envs\spy\lib\site-packages\requests\sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\spy\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\ProgramData\Anaconda3\envs\spy\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\spy\lib\site-packages\requests\adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2020-10-25 11:53:22,543 - Shuake.py[line:260] - INFO: 15037671931	刷课意外
2020-10-25 11:55:03,349 - Shuake.py[line:259] - ERROR: 
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\spy\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "D:\ProgramData\Anaconda3\envs\spy\lib\site-packages\urllib3\connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "D:\ProgramData\Anaconda3\envs\spy\lib\site-packages\urllib3\connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "D:\ProgramData\Anaconda3\envs\spy\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "D:\ProgramData\Anaconda3\envs\spy\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "D:\ProgramData\Anaconda3\envs\spy\lib\http\client.py", line 265, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\spy\lib\site-packages\requests\adapters.py", line 445, in send
    timeout=timeout
  File "D:\ProgramData\Anaconda3\envs\spy\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "D:\ProgramData\Anaconda3\envs\spy\lib\site-packages\urllib3\util\retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "D:\ProgramData\Anaconda3\envs\spy\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "D:\ProgramData\Anaconda3\envs\spy\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "D:\ProgramData\Anaconda3\envs\spy\lib\site-packages\urllib3\connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "D:\ProgramData\Anaconda3\envs\spy\lib\site-packages\urllib3\connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "D:\ProgramData\Anaconda3\envs\spy\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "D:\ProgramData\Anaconda3\envs\spy\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "D:\ProgramData\Anaconda3\envs\spy\lib\http\client.py", line 265, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 253, in shuake
    self.watch_video(cardInfo, reportInfo, knowledge, scoreInfo)
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 309, in watch_video
    params=params)
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 30, in get
    return super(Session,self).get(*args,**kwargs,timeout=self.timeOut)
  File "D:\ProgramData\Anaconda3\envs\spy\lib\site-packages\requests\sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\spy\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\ProgramData\Anaconda3\envs\spy\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\spy\lib\site-packages\requests\adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2020-10-25 11:55:03,351 - Shuake.py[line:260] - INFO: 18182699011	刷课意外
2020-10-25 11:55:08,465 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 11:55:08,466 - Shuake.py[line:580] - INFO: 17809297831	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 12:00:09,691 - Shuake.py[line:579] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 563, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 12:00:09,692 - Shuake.py[line:580] - INFO: 17809297831	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 12:01:00,575 - Shuake.py[line:666] - INFO: 运行
2020-10-25 12:01:09,298 - Shuake.py[line:589] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 573, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 12:01:09,300 - Shuake.py[line:590] - INFO: 15081150997	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 12:01:29,880 - Shuake.py[line:589] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 573, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 12:01:29,881 - Shuake.py[line:590] - INFO: 15970198033	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 12:02:06,136 - Shuake.py[line:589] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 573, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 12:02:06,137 - Shuake.py[line:590] - INFO: 18740455867	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 12:02:12,564 - Shuake.py[line:589] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 573, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 12:02:12,564 - Shuake.py[line:590] - INFO: 17809297831	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 12:02:12,872 - Shuake.py[line:589] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 573, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 12:02:12,873 - Shuake.py[line:590] - INFO: 17809297831	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 12:03:01,929 - Shuake.py[line:589] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 573, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 12:03:01,929 - Shuake.py[line:590] - INFO: 18845142702	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 12:17:42,922 - Shuake.py[line:589] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 573, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 12:17:42,923 - Shuake.py[line:590] - INFO: 17691183327	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 12:20:28,745 - Shuake.py[line:589] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 573, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 12:20:28,746 - Shuake.py[line:590] - INFO: 18700182108	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 12:23:08,706 - Shuake.py[line:589] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 573, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 12:23:08,706 - Shuake.py[line:590] - INFO: 15638127287	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 12:23:11,227 - Shuake.py[line:589] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 573, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 12:23:11,228 - Shuake.py[line:590] - INFO: 13098880838	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 12:29:30,126 - Shuake.py[line:589] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 573, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 12:29:30,128 - Shuake.py[line:590] - INFO: 15702959565	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 12:34:12,933 - Shuake.py[line:589] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 573, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 12:34:12,934 - Shuake.py[line:590] - INFO: 18182699011	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 12:37:14,715 - Shuake.py[line:589] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 573, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 12:37:14,716 - Shuake.py[line:590] - INFO: 15829380839	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 12:38:58,412 - Shuake.py[line:354] - ERROR: 题目：什么是基本款
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 337, in answer
    if response["success"]==200 and response["msg"].find("维护")<0:
KeyError: 'msg'
2020-10-25 12:38:58,413 - Shuake.py[line:355] - ERROR: 搜索答案出错
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 337, in answer
    if response["success"]==200 and response["msg"].find("维护")<0:
KeyError: 'msg'
2020-10-25 12:38:58,414 - Shuake.py[line:472] - ERROR: 女生穿搭技巧	基本款－你衣柜里必备的衣服	什么是基本款	4.1.1章节测验
2020-10-25 12:38:58,415 - Shuake.py[line:473] - ERROR: 答题出错
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 419, in dati
    assert questionAnswer is not None
AssertionError
2020-10-25 12:41:14,987 - Shuake.py[line:589] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 573, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 12:41:14,988 - Shuake.py[line:590] - INFO: 17809297831	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 12:48:00,662 - Shuake.py[line:354] - ERROR: 题目：贴合身体曲线的衬衫，以单色为主，称为（  ）款衬衫。
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 337, in answer
    if response["success"]==200 and response["msg"].find("维护")<0:
KeyError: 'msg'
2020-10-25 12:48:00,663 - Shuake.py[line:355] - ERROR: 搜索答案出错
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 337, in answer
    if response["success"]==200 and response["msg"].find("维护")<0:
KeyError: 'msg'
2020-10-25 12:48:00,664 - Shuake.py[line:472] - ERROR: 女生穿搭技巧	基本款－你衣柜里必备的衣服	不同衬衫的穿法	4.2.1章节测验
2020-10-25 12:48:00,664 - Shuake.py[line:473] - ERROR: 答题出错
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 419, in dati
    assert questionAnswer is not None
AssertionError
2020-10-25 12:51:02,321 - Shuake.py[line:354] - ERROR: 题目：掩盖腿粗缺陷的服装款式是（  ）
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 337, in answer
    if response["success"]==200 and response["msg"].find("维护")<0:
KeyError: 'msg'
2020-10-25 12:51:02,322 - Shuake.py[line:355] - ERROR: 搜索答案出错
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 337, in answer
    if response["success"]==200 and response["msg"].find("维护")<0:
KeyError: 'msg'
2020-10-25 12:51:02,323 - Shuake.py[line:472] - ERROR: 女生穿搭技巧	基本款－你衣柜里必备的衣服	裙子的长度显高矮	4.3.1章节测验
2020-10-25 12:51:02,323 - Shuake.py[line:473] - ERROR: 答题出错
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 419, in dati
    assert questionAnswer is not None
AssertionError
2020-10-25 13:00:04,236 - Shuake.py[line:589] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 573, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 13:00:04,237 - Shuake.py[line:590] - INFO: 15970198033	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 13:00:04,574 - Shuake.py[line:354] - ERROR: 题目：搭配长裤的袜子应该是（  ），才能和裤子保持协调。
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 337, in answer
    if response["success"]==200 and response["msg"].find("维护")<0:
KeyError: 'msg'
2020-10-25 13:00:04,576 - Shuake.py[line:355] - ERROR: 搜索答案出错
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 337, in answer
    if response["success"]==200 and response["msg"].find("维护")<0:
KeyError: 'msg'
2020-10-25 13:00:04,577 - Shuake.py[line:472] - ERROR: 女生穿搭技巧	基本款－你衣柜里必备的衣服	裤子的着装要求	4.4.1章节测验
2020-10-25 13:00:04,578 - Shuake.py[line:473] - ERROR: 答题出错
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 419, in dati
    assert questionAnswer is not None
AssertionError
2020-10-25 13:03:05,913 - Shuake.py[line:354] - ERROR: 题目：个子娇小、瘦弱的女生，适合（）搭配短裙和连衣裙，有年轻与活力的感觉。
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 337, in answer
    if response["success"]==200 and response["msg"].find("维护")<0:
KeyError: 'msg'
2020-10-25 13:03:05,914 - Shuake.py[line:355] - ERROR: 搜索答案出错
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 337, in answer
    if response["success"]==200 and response["msg"].find("维护")<0:
KeyError: 'msg'
2020-10-25 13:03:05,915 - Shuake.py[line:472] - ERROR: 女生穿搭技巧	基本款－你衣柜里必备的衣服	西装的颜色与长短	4.5.1章节测验
2020-10-25 13:03:05,915 - Shuake.py[line:473] - ERROR: 答题出错
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 419, in dati
    assert questionAnswer is not None
AssertionError
2020-10-25 13:04:54,728 - Shuake.py[line:589] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 573, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 13:04:54,729 - Shuake.py[line:590] - INFO: 15970198033	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 13:07:07,286 - Shuake.py[line:354] - ERROR: 题目：直接贴皮肤穿，没有扎的感觉的针织衫是（ ）。
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 337, in answer
    if response["success"]==200 and response["msg"].find("维护")<0:
KeyError: 'msg'
2020-10-25 13:07:07,287 - Shuake.py[line:355] - ERROR: 搜索答案出错
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 337, in answer
    if response["success"]==200 and response["msg"].find("维护")<0:
KeyError: 'msg'
2020-10-25 13:07:07,288 - Shuake.py[line:472] - ERROR: 女生穿搭技巧	基本款－你衣柜里必备的衣服	针织开衫	4.6.1章节测验
2020-10-25 13:07:07,288 - Shuake.py[line:473] - ERROR: 答题出错
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 419, in dati
    assert questionAnswer is not None
AssertionError
2020-10-25 13:09:08,472 - Shuake.py[line:354] - ERROR: 题目：黄色皮肤的女生适合风衣的颜色有（）。
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 337, in answer
    if response["success"]==200 and response["msg"].find("维护")<0:
KeyError: 'msg'
2020-10-25 13:09:08,474 - Shuake.py[line:355] - ERROR: 搜索答案出错
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 337, in answer
    if response["success"]==200 and response["msg"].find("维护")<0:
KeyError: 'msg'
2020-10-25 13:09:08,477 - Shuake.py[line:472] - ERROR: 女生穿搭技巧	基本款－你衣柜里必备的衣服	风衣的颜色	4.7.1章节测验
2020-10-25 13:09:08,478 - Shuake.py[line:473] - ERROR: 答题出错
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 419, in dati
    assert questionAnswer is not None
AssertionError
2020-10-25 13:16:10,346 - Shuake.py[line:354] - ERROR: 题目：吊带裙搭配白T恤，适合（  ）的女生。
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 337, in answer
    if response["success"]==200 and response["msg"].find("维护")<0:
KeyError: 'msg'
2020-10-25 13:16:10,348 - Shuake.py[line:355] - ERROR: 搜索答案出错
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 337, in answer
    if response["success"]==200 and response["msg"].find("维护")<0:
KeyError: 'msg'
2020-10-25 13:16:10,350 - Shuake.py[line:472] - ERROR: 女生穿搭技巧	基本款－你衣柜里必备的衣服	T恤的穿搭方法	4.8.1章节测验
2020-10-25 13:16:10,350 - Shuake.py[line:473] - ERROR: 答题出错
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 419, in dati
    assert questionAnswer is not None
AssertionError
2020-10-25 13:19:16,699 - Shuake.py[line:589] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 573, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 13:19:16,702 - Shuake.py[line:590] - INFO: 15037671931	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 13:19:17,359 - Shuake.py[line:589] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 573, in get_chapters_info
    chapters_a = chapters_lxml.find_all(name="a")
AttributeError: 'NoneType' object has no attribute 'find_all'
2020-10-25 13:19:17,359 - Shuake.py[line:590] - INFO: 17561925661	获取chapter_info 失败  可能是资源下线，不是程序错误
2020-10-25 13:23:12,286 - Shuake.py[line:354] - ERROR: 题目：适合办公室穿的连衣裙应该是（   ）的设计款式。
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 337, in answer
    if response["success"]==200 and response["msg"].find("维护")<0:
KeyError: 'msg'
2020-10-25 13:23:12,287 - Shuake.py[line:355] - ERROR: 搜索答案出错
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 337, in answer
    if response["success"]==200 and response["msg"].find("维护")<0:
KeyError: 'msg'
2020-10-25 13:23:12,288 - Shuake.py[line:472] - ERROR: 女生穿搭技巧	基本款－你衣柜里必备的衣服	基本款清单	4.1.2章节测验
2020-10-25 13:23:12,289 - Shuake.py[line:473] - ERROR: 答题出错
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 419, in dati
    assert questionAnswer is not None
AssertionError
2020-10-25 13:25:40,633 - Shuake.py[line:666] - INFO: 运行
2020-10-25 13:25:43,270 - Shuake.py[line:354] - ERROR: 题目：什么是基本款
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 337, in answer
    if response["success"]==200 and response["msg"].find("维护")<0:
KeyError: 'msg'
2020-10-25 13:25:43,273 - Shuake.py[line:355] - ERROR: 搜索答案出错
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 337, in answer
    if response["success"]==200 and response["msg"].find("维护")<0:
KeyError: 'msg'
2020-10-25 13:25:43,274 - Shuake.py[line:472] - ERROR: 女生穿搭技巧	基本款－你衣柜里必备的衣服	什么是基本款	4.1.1章节测验
2020-10-25 13:25:43,274 - Shuake.py[line:473] - ERROR: 答题出错
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 419, in dati
    assert questionAnswer is not None
AssertionError
2020-10-25 13:25:45,195 - Shuake.py[line:354] - ERROR: 题目：贴合身体曲线的衬衫，以单色为主，称为（  ）款衬衫。
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 337, in answer
    if response["success"]==200 and response["msg"].find("维护")<0:
KeyError: 'msg'
2020-10-25 13:25:45,196 - Shuake.py[line:355] - ERROR: 搜索答案出错
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 337, in answer
    if response["success"]==200 and response["msg"].find("维护")<0:
KeyError: 'msg'
2020-10-25 13:25:45,197 - Shuake.py[line:472] - ERROR: 女生穿搭技巧	基本款－你衣柜里必备的衣服	不同衬衫的穿法	4.2.1章节测验
2020-10-25 13:25:45,197 - Shuake.py[line:473] - ERROR: 答题出错
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 419, in dati
    assert questionAnswer is not None
AssertionError
2020-10-25 13:25:47,114 - Shuake.py[line:354] - ERROR: 题目：掩盖腿粗缺陷的服装款式是（  ）
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 337, in answer
    if response["success"]==200 and response["msg"].find("维护")<0:
KeyError: 'msg'
2020-10-25 13:25:47,115 - Shuake.py[line:355] - ERROR: 搜索答案出错
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 337, in answer
    if response["success"]==200 and response["msg"].find("维护")<0:
KeyError: 'msg'
2020-10-25 13:25:47,116 - Shuake.py[line:472] - ERROR: 女生穿搭技巧	基本款－你衣柜里必备的衣服	裙子的长度显高矮	4.3.1章节测验
2020-10-25 13:25:47,116 - Shuake.py[line:473] - ERROR: 答题出错
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 419, in dati
    assert questionAnswer is not None
AssertionError
2020-10-25 13:26:57,053 - Shuake.py[line:666] - INFO: 运行
2020-10-25 13:28:11,594 - Shuake.py[line:666] - INFO: 运行
2020-10-25 13:39:33,984 - Shuake.py[line:666] - INFO: 运行
2020-10-25 13:41:50,703 - Shuake.py[line:666] - INFO: 运行
2020-10-25 13:42:30,165 - Shuake.py[line:666] - INFO: 运行
2020-10-25 13:43:29,848 - Shuake.py[line:666] - INFO: 运行
2020-10-25 13:45:02,817 - Shuake.py[line:666] - INFO: 运行
2020-10-25 13:46:51,612 - Shuake.py[line:666] - INFO: 运行
2020-10-25 13:53:17,617 - Shuake.py[line:667] - INFO: 运行
2020-10-25 13:54:18,034 - Shuake.py[line:667] - INFO: 运行
2020-10-25 13:54:32,986 - Shuake.py[line:171] - ERROR: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 164, in init_knowledegList
    "label": float(knowlege["label"]),
ValueError: could not convert string to float: '2.1.1'
2020-10-25 13:54:32,989 - Shuake.py[line:172] - INFO: 18925468581	获取课程列表失败
2020-10-25 14:00:44,825 - Shuake.py[line:671] - INFO: 运行
2020-10-25 14:01:13,602 - Shuake.py[line:175] - ERROR: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 171, in init_knowledegList
    self.knowlegeList[course["id"]].sort(key=knowledeg_sort)
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 144, in knowledeg_sort
    labels=labels.repalce(".","")
AttributeError: 'str' object has no attribute 'repalce'
2020-10-25 14:01:33,334 - Shuake.py[line:671] - INFO: 运行
2020-10-25 14:04:35,109 - Shuake.py[line:671] - INFO: 运行
2020-10-25 14:08:21,564 - Shuake.py[line:671] - INFO: 运行
2020-10-25 14:13:45,922 - Shuake.py[line:672] - INFO: 运行
2020-10-25 14:21:45,050 - Shuake.py[line:681] - INFO: 运行
2020-10-25 14:22:43,728 - Shuake.py[line:681] - INFO: 运行
2020-10-25 14:27:53,081 - Shuake.py[line:681] - INFO: 运行
2020-10-25 14:32:58,439 - Shuake.py[line:487] - ERROR: 女生穿搭技巧	基本款－你衣柜里必备的衣服	衬衫穿搭注意事项	4.2.3章节测验
2020-10-25 14:32:58,439 - Shuake.py[line:488] - ERROR: 答题出错
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 404, in dati
    ('workAnswerId', params_info["workAnswerId"]),
KeyError: 'workAnswerId'
2020-10-25 14:34:03,601 - Shuake.py[line:681] - INFO: 运行
2020-10-25 14:48:00,403 - Shuake.py[line:487] - ERROR: 女生穿搭技巧	基本款－你衣柜里必备的衣服	短裙	4.3.3章节测验
2020-10-25 14:48:00,403 - Shuake.py[line:488] - ERROR: 答题出错
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 404, in dati
    ('workAnswerId', params_info["workAnswerId"]),
KeyError: 'workAnswerId'
2020-10-25 14:55:01,923 - Shuake.py[line:487] - ERROR: 女生穿搭技巧	基本款－你衣柜里必备的衣服	中长裙	4.3.4章节测验
2020-10-25 14:55:01,923 - Shuake.py[line:488] - ERROR: 答题出错
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 404, in dati
    ('workAnswerId', params_info["workAnswerId"]),
KeyError: 'workAnswerId'
2020-10-25 14:55:27,604 - Shuake.py[line:680] - INFO: 运行
2020-10-25 15:51:40,264 - Shuake.py[line:680] - INFO: 运行
2020-10-25 16:02:45,397 - Shuake.py[line:683] - INFO: 运行
2020-10-25 18:59:05,551 - Shuake.py[line:683] - INFO: 运行
2020-10-25 19:07:51,278 - Shuake.py[line:683] - INFO: 运行
2020-10-25 19:08:53,766 - Shuake.py[line:92] - ERROR: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 83, in login
    self.puid = re.search(r"puid\":(.*?),", resp).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2020-10-25 19:08:53,768 - Shuake.py[line:93] - INFO: 13098880838登陆失败
2020-10-25 19:08:53,768 - Shuake.py[line:670] - INFO: 梗慧	： 密码错误
2020-10-25 19:09:13,054 - Shuake.py[line:683] - INFO: 运行
2020-10-25 21:47:55,295 - Shuake.py[line:489] - ERROR: 女生穿搭技巧	职场俏佳人	职业装穿搭注意事项	8.2.4章节测验
2020-10-25 21:47:55,295 - Shuake.py[line:490] - ERROR: 答题出错
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 479, in dati
    assert flag == 1  # 若发生异常  答案没找到
AssertionError
2020-10-25 22:19:24,083 - Shuake.py[line:683] - INFO: 运行
2020-10-25 22:22:21,381 - Shuake.py[line:683] - INFO: 运行
2020-10-25 22:22:49,197 - Shuake.py[line:489] - ERROR: 女生穿搭技巧	职场俏佳人	职业装穿搭注意事项	8.2.4章节测验
2020-10-25 22:22:49,197 - Shuake.py[line:490] - ERROR: 答题出错
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 479, in dati
    assert flag == 1  # 若发生异常  答案没找到
AssertionError
2020-10-25 22:23:27,784 - Shuake.py[line:683] - INFO: 运行
2020-10-25 22:31:35,391 - Shuake.py[line:683] - INFO: 运行
2020-10-26 03:49:36,380 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:49:36,382 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:49:42,299 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:49:42,299 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:49:47,367 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:49:47,367 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:49:52,435 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:49:52,436 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:49:57,507 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:49:57,508 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:50:02,706 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:50:02,706 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:50:07,777 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:50:07,777 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:50:12,859 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:50:12,859 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:50:17,932 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:50:17,933 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:50:23,003 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:50:23,003 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:50:28,072 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:50:28,073 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:50:33,329 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:50:33,329 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:50:38,402 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:50:38,402 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:50:43,476 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:50:43,476 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:50:48,645 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:50:48,645 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:50:53,717 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:50:53,717 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:50:58,789 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:50:58,790 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:51:03,861 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:51:03,861 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:51:09,149 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:51:09,149 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:51:14,239 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:51:14,240 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:51:19,311 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:51:19,311 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:51:24,385 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:51:24,386 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:51:29,639 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:51:29,640 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:51:34,711 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:51:34,712 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:51:39,788 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:51:39,789 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:51:44,860 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:51:44,860 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:51:49,929 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:51:49,930 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:51:54,999 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:51:55,000 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:52:00,070 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:52:00,070 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:52:05,155 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:52:05,155 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:52:10,326 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:52:10,327 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:52:15,398 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:52:15,398 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:52:20,469 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:52:20,469 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:52:25,540 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:52:25,540 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:52:30,607 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:52:30,607 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:52:35,682 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:52:35,682 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:52:40,753 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:52:40,754 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:52:45,965 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:52:45,965 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:52:51,036 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:52:51,037 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:52:56,108 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:52:56,108 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:53:01,179 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:53:01,180 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:53:06,250 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:53:06,251 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:53:11,512 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:53:11,513 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:53:16,586 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:53:16,587 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:53:21,662 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:53:21,662 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:53:26,730 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:53:26,731 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:53:31,801 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:53:31,802 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:53:36,872 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:53:36,873 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:53:41,942 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:53:41,942 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:53:47,014 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:53:47,014 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:53:52,083 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:53:52,083 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:53:57,153 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:53:57,154 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:54:02,225 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:54:02,225 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:54:07,487 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:54:07,488 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:54:12,562 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:54:12,562 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:54:17,632 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:54:17,632 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:54:22,704 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:54:22,705 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:54:27,779 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:54:27,779 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:54:32,849 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:54:32,850 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:54:37,923 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:54:37,924 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:54:42,993 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:54:42,994 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:54:48,062 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:54:48,063 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:54:53,229 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:54:53,229 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:54:58,301 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:54:58,301 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:55:03,375 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:55:03,376 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:55:08,446 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:55:08,446 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:55:13,516 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:55:13,516 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:55:18,588 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:55:18,588 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:55:23,671 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:55:23,671 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:55:28,837 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:55:28,837 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:55:33,917 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:55:33,918 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:55:38,987 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:55:38,988 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:55:44,059 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:55:44,059 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:55:49,128 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:55:49,129 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:55:54,203 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:55:54,204 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:55:59,482 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:55:59,483 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:56:04,690 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:56:04,691 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:56:09,759 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:56:09,759 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:56:14,829 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:56:14,830 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:56:19,903 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:56:19,904 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:56:24,974 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:56:24,975 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:56:30,042 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:56:30,043 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:56:35,113 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:56:35,113 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:56:40,185 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:56:40,185 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:56:45,261 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:56:45,261 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:56:50,561 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:56:50,561 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:56:55,632 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:56:55,633 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:57:00,801 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:57:00,802 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:57:05,876 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:57:05,877 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:57:10,945 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:57:10,946 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:57:16,015 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:57:16,016 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:57:21,183 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:57:21,184 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:57:26,257 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:57:26,258 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:57:31,330 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:57:31,331 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:57:36,403 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:57:36,404 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:57:41,473 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:57:41,474 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:57:46,541 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:57:46,541 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:57:51,807 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:57:51,808 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:57:56,876 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:57:56,877 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:58:01,947 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:58:01,947 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:58:07,301 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:58:07,301 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:58:12,372 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:58:12,372 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:58:17,481 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:58:17,481 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:58:22,554 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:58:22,554 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:58:27,726 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:58:27,726 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:58:32,797 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:58:32,797 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:58:37,866 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:58:37,867 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:58:42,935 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:58:42,935 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:58:48,008 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:58:48,008 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:58:53,079 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:58:53,079 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:58:58,149 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:58:58,149 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:59:03,298 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:59:03,299 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:59:08,571 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:59:08,571 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:59:13,643 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:59:13,643 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:59:18,712 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:59:18,713 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:59:23,783 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:59:23,784 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:59:28,856 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:59:28,856 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:59:33,925 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:59:33,925 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:59:38,995 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:59:38,996 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:59:44,067 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:59:44,067 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:59:49,138 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:59:49,139 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:59:54,213 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:59:54,214 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 03:59:59,604 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 03:59:59,604 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:00:04,756 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:00:04,757 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:00:09,830 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:00:09,831 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:00:14,904 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:00:14,904 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:00:19,976 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:00:19,977 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:00:25,140 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:00:25,140 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:00:33,227 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:00:33,228 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:00:38,513 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:00:38,513 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:00:43,588 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:00:43,588 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:00:48,660 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:00:48,660 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:00:53,734 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:00:53,734 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:00:59,130 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:00:59,130 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:01:04,386 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:01:04,387 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:01:09,537 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:01:09,538 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:01:14,703 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:01:14,704 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:01:19,770 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:01:19,771 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:01:24,841 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:01:24,841 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:01:29,912 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:01:29,912 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:01:34,984 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:01:34,984 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:01:40,051 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:01:40,051 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:01:45,222 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:01:45,222 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:01:50,292 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:01:50,292 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:01:55,455 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:01:55,455 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:02:00,526 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:02:00,526 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:02:05,595 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:02:05,595 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:02:10,851 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:02:10,851 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:02:15,925 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:02:15,925 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:02:20,996 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:02:20,997 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:02:26,268 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:02:26,269 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:02:31,340 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:02:31,341 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:02:36,411 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:02:36,411 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:02:41,702 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:02:41,703 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:02:46,773 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:02:46,774 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:02:51,846 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:02:51,847 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:02:56,916 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:02:56,917 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:03:02,190 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:03:02,190 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:03:07,267 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:03:07,267 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:03:12,336 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:03:12,337 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:03:17,407 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:03:17,408 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:03:22,478 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:03:22,479 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:03:27,550 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:03:27,551 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:03:32,620 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:03:32,620 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:03:37,688 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:03:37,688 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:03:42,759 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:03:42,760 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:03:47,831 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:03:47,832 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:03:52,900 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:03:52,900 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:03:57,972 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:03:57,972 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:04:03,370 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:04:03,371 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:04:08,440 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:04:08,441 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:04:13,606 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:04:13,607 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:04:18,678 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:04:18,678 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:04:23,746 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:04:23,747 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:04:28,822 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:04:28,822 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:04:34,085 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:04:34,086 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:04:39,158 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:04:39,158 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:04:44,227 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:04:44,228 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:04:49,298 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:04:49,298 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:04:54,372 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:04:54,372 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:04:59,790 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:04:59,790 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:05:04,957 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:05:04,958 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:05:10,028 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:05:10,028 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:05:15,096 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:05:15,096 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:05:20,352 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:05:20,352 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:05:25,422 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:05:25,423 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:05:30,495 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:05:30,496 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:05:35,564 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:05:35,565 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:05:40,642 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:05:40,643 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:05:45,713 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:05:45,713 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:05:50,790 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:05:50,790 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:05:55,859 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:05:55,859 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:06:00,930 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:06:00,930 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:06:06,000 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:06:06,001 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:06:11,073 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:06:11,074 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:06:16,186 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:06:16,187 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:06:21,351 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:06:21,351 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:06:26,428 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:06:26,428 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:06:31,499 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:06:31,500 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:06:36,566 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:06:36,567 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:06:41,751 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:06:41,751 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:06:46,820 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:06:46,820 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:06:51,894 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:06:51,895 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:06:56,967 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:06:56,967 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:07:02,244 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:07:02,245 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:07:07,317 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:07:07,318 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:07:12,390 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:07:12,390 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:07:17,463 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:07:17,463 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:07:22,540 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:07:22,540 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:07:27,611 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:07:27,612 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:07:32,872 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:07:32,872 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:07:38,217 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:07:38,217 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:07:43,384 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:07:43,384 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:07:48,452 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:07:48,452 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:07:53,522 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:07:53,523 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:07:58,591 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:07:58,591 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:08:03,753 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:08:03,754 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:08:08,826 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:08:08,827 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:08:13,898 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:08:13,898 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:08:18,967 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:08:18,967 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:08:24,043 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:08:24,044 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:08:29,113 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:08:29,114 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:08:34,279 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:08:34,279 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:08:39,352 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:08:39,352 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:08:44,424 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:08:44,425 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
2020-10-26 04:08:49,496 - Shuake.py[line:569] - INFO: 
Traceback (most recent call last):
  File "D:/bin/chaoxing_auto_Shuake/com/main/Shuake.py", line 566, in get_read_time
    read_time = int(re.search(r"secondReadTime = \"(.*?)\"", response.text).group(1))
ValueError: invalid literal for int() with base 10: ''
2020-10-26 04:08:49,496 - Shuake.py[line:570] - INFO: 18925468581	获取分数信息失败
